// â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// UNIVERSO DE AÃ‡Ã•ES
// â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

export const UNIVERSE = [
  // GROWTH
  { ticker: 'NVDA',  name: 'Nvidia',                 type: 'growth', sector: 'Technology' },
  { ticker: 'AAPL',  name: 'Apple',                  type: 'growth', sector: 'Technology' },
  { ticker: 'GOOGL', name: 'Alphabet',               type: 'growth', sector: 'Technology' },
  { ticker: 'MSFT',  name: 'Microsoft',              type: 'growth', sector: 'Technology' },
  { ticker: 'AMZN',  name: 'Amazon',                 type: 'growth', sector: 'Technology' },
  { ticker: 'AVGO',  name: 'Broadcom',               type: 'growth', sector: 'Technology' },
  { ticker: 'META',  name: 'Meta',                   type: 'growth', sector: 'Technology' },
  { ticker: 'TSLA',  name: 'Tesla',                  type: 'growth', sector: 'Consumer' },
  { ticker: 'AMD',   name: 'AMD',                    type: 'growth', sector: 'Technology' },
  { ticker: 'NFLX',  name: 'Netflix',                type: 'growth', sector: 'Technology' },
  { ticker: 'PLTR',  name: 'Palantir',               type: 'growth', sector: 'Technology' },
  { ticker: 'CRM',   name: 'Salesforce',             type: 'growth', sector: 'Technology' },
  { ticker: 'ADBE',  name: 'Adobe',                  type: 'growth', sector: 'Technology' },
  { ticker: 'ORCL',  name: 'Oracle',                 type: 'growth', sector: 'Technology' },
  { ticker: 'LRCX',  name: 'Lam Research',           type: 'growth', sector: 'Technology' },
  { ticker: 'AMAT',  name: 'Applied Materials',      type: 'growth', sector: 'Technology' },
  { ticker: 'KLAC',  name: 'KLA Corporation',        type: 'growth', sector: 'Technology' },
  { ticker: 'ANET',  name: 'Arista Networks',        type: 'growth', sector: 'Technology' },
  { ticker: 'ISRG',  name: 'Intuitive Surgical',     type: 'growth', sector: 'Healthcare' },
  { ticker: 'NOW',   name: 'ServiceNow',             type: 'growth', sector: 'Technology' },
  { ticker: 'PANW',  name: 'Palo Alto Networks',     type: 'growth', sector: 'Technology' },
  { ticker: 'MRVL',  name: 'Marvell Technology',     type: 'growth', sector: 'Technology' },
  { ticker: 'MU',    name: 'Micron Technology',      type: 'growth', sector: 'Technology' },
  { ticker: 'UBER',  name: 'Uber',                   type: 'growth', sector: 'Technology' },
  { ticker: 'LLY',   name: 'Eli Lilly',              type: 'growth', sector: 'Healthcare' },
  { ticker: 'COST',  name: 'Costco',                 type: 'growth', sector: 'Consumer' },
  { ticker: 'TMUS',  name: 'T-Mobile',               type: 'growth', sector: 'Telecom' },
  { ticker: 'GEV',   name: 'GE Vernova',             type: 'growth', sector: 'Industrials' },
  { ticker: 'GE',    name: 'GE Aerospace',           type: 'growth', sector: 'Industrials' },
  { ticker: 'APP',   name: 'AppLovin',               type: 'growth', sector: 'Technology' },
  { ticker: 'CRWD',  name: 'CrowdStrike',            type: 'growth', sector: 'Technology' },
  { ticker: 'INTU',  name: 'Intuit',                 type: 'growth', sector: 'Technology' },
  { ticker: 'ADSK',  name: 'Autodesk',               type: 'growth', sector: 'Technology' },
  { ticker: 'WDAY',  name: 'Workday',                type: 'growth', sector: 'Technology' },
  { ticker: 'DDOG',  name: 'Datadog',                type: 'growth', sector: 'Technology' },
  { ticker: 'TTD',   name: 'The Trade Desk',         type: 'growth', sector: 'Technology' },
  { ticker: 'VRTX',  name: 'Vertex Pharmaceuticals', type: 'growth', sector: 'Healthcare' },
  { ticker: 'REGN',  name: 'Regeneron',              type: 'growth', sector: 'Healthcare' },
  { ticker: 'BSX',   name: 'Boston Scientific',      type: 'growth', sector: 'Healthcare' },
  { ticker: 'HCA',   name: 'HCA Healthcare',         type: 'growth', sector: 'Healthcare' },
  { ticker: 'SYK',   name: 'Stryker',                type: 'growth', sector: 'Healthcare' },
  { ticker: 'CEG',   name: 'Constellation Energy',   type: 'growth', sector: 'Utilities' },
  { ticker: 'DELL',  name: 'Dell Technologies',      type: 'growth', sector: 'Technology' },
  { ticker: 'APH',   name: 'Amphenol',               type: 'growth', sector: 'Technology' },
  { ticker: 'ADI',   name: 'Analog Devices',         type: 'growth', sector: 'Technology' },
  { ticker: 'QCOM',  name: 'Qualcomm',               type: 'growth', sector: 'Technology' },
  { ticker: 'SPGI',  name: 'S&P Global',             type: 'growth', sector: 'Finance' },
  { ticker: 'CME',   name: 'CME Group',              type: 'growth', sector: 'Finance' },
  { ticker: 'MCO',   name: "Moody's",                type: 'growth', sector: 'Finance' },
  { ticker: 'BLK',   name: 'BlackRock',              type: 'growth', sector: 'Finance' },
  { ticker: 'BKNG',  name: 'Booking Holdings',       type: 'growth', sector: 'Consumer' },
  { ticker: 'SBUX',  name: 'Starbucks',              type: 'growth', sector: 'Consumer' },
  { ticker: 'NKE',   name: 'Nike',                   type: 'growth', sector: 'Consumer' },
  { ticker: 'LULU',  name: 'Lululemon',              type: 'growth', sector: 'Consumer' },
  { ticker: 'ELV',   name: 'Elevance Health',        type: 'growth', sector: 'Healthcare' },
  { ticker: 'FICO',  name: 'Fair Isaac (FICO)',       type: 'growth', sector: 'Technology' },
  { ticker: 'HWM',   name: 'Howmet Aerospace',       type: 'growth', sector: 'Industrials' },
  // VALUE
  { ticker: 'BRK-B', name: 'Berkshire Hathaway',     type: 'value',  sector: 'Finance' },
  { ticker: 'JPM',   name: 'JPMorgan Chase',         type: 'value',  sector: 'Finance' },
  { ticker: 'BAC',   name: 'Bank of America',        type: 'value',  sector: 'Finance' },
  { ticker: 'WFC',   name: 'Wells Fargo',            type: 'value',  sector: 'Finance' },
  { ticker: 'GS',    name: 'Goldman Sachs',          type: 'value',  sector: 'Finance' },
  { ticker: 'MS',    name: 'Morgan Stanley',         type: 'value',  sector: 'Finance' },
  { ticker: 'C',     name: 'Citigroup',              type: 'value',  sector: 'Finance' },
  { ticker: 'AXP',   name: 'American Express',       type: 'value',  sector: 'Finance' },
  { ticker: 'SCHW',  name: 'Charles Schwab',         type: 'value',  sector: 'Finance' },
  { ticker: 'COF',   name: 'Capital One',            type: 'value',  sector: 'Finance' },
  { ticker: 'USB',   name: 'US Bancorp',             type: 'value',  sector: 'Finance' },
  { ticker: 'PNC',   name: 'PNC Financial',          type: 'value',  sector: 'Finance' },
  { ticker: 'CB',    name: 'Chubb',                  type: 'value',  sector: 'Finance' },
  { ticker: 'PGR',   name: 'Progressive',            type: 'value',  sector: 'Finance' },
  { ticker: 'MET',   name: 'MetLife',                type: 'value',  sector: 'Finance' },
  { ticker: 'AFL',   name: 'Aflac',                  type: 'value',  sector: 'Finance' },
  { ticker: 'V',     name: 'Visa',                   type: 'value',  sector: 'Finance' },
  { ticker: 'MA',    name: 'Mastercard',             type: 'value',  sector: 'Finance' },
  { ticker: 'XOM',   name: 'Exxon Mobil',            type: 'value',  sector: 'Energy' },
  { ticker: 'CVX',   name: 'Chevron',                type: 'value',  sector: 'Energy' },
  { ticker: 'COP',   name: 'ConocoPhillips',         type: 'value',  sector: 'Energy' },
  { ticker: 'EOG',   name: 'EOG Resources',          type: 'value',  sector: 'Energy' },
  { ticker: 'SLB',   name: 'SLB',                    type: 'value',  sector: 'Energy' },
  { ticker: 'MPC',   name: 'Marathon Petroleum',     type: 'value',  sector: 'Energy' },
  { ticker: 'OXY',   name: 'Occidental Petroleum',   type: 'value',  sector: 'Energy' },
  { ticker: 'CAT',   name: 'Caterpillar',            type: 'value',  sector: 'Industrials' },
  { ticker: 'RTX',   name: 'RTX Corporation',        type: 'value',  sector: 'Industrials' },
  { ticker: 'HON',   name: 'Honeywell',              type: 'value',  sector: 'Industrials' },
  { ticker: 'LMT',   name: 'Lockheed Martin',        type: 'value',  sector: 'Industrials' },
  { ticker: 'NOC',   name: 'Northrop Grumman',       type: 'value',  sector: 'Industrials' },
  { ticker: 'GD',    name: 'General Dynamics',       type: 'value',  sector: 'Industrials' },
  { ticker: 'BA',    name: 'Boeing',                 type: 'value',  sector: 'Industrials' },
  { ticker: 'UPS',   name: 'UPS',                    type: 'value',  sector: 'Industrials' },
  { ticker: 'UNP',   name: 'Union Pacific',          type: 'value',  sector: 'Industrials' },
  { ticker: 'DE',    name: 'John Deere',             type: 'value',  sector: 'Industrials' },
  { ticker: 'ETN',   name: 'Eaton Corporation',      type: 'value',  sector: 'Industrials' },
  { ticker: 'ITW',   name: 'Illinois Tool Works',    type: 'value',  sector: 'Industrials' },
  { ticker: 'EMR',   name: 'Emerson Electric',       type: 'value',  sector: 'Industrials' },
  { ticker: 'WM',    name: 'Waste Management',       type: 'value',  sector: 'Industrials' },
  { ticker: 'IBM',   name: 'IBM',                    type: 'value',  sector: 'Technology' },
  { ticker: 'INTC',  name: 'Intel',                  type: 'value',  sector: 'Technology' },
  { ticker: 'CSCO',  name: 'Cisco',                  type: 'value',  sector: 'Technology' },
  { ticker: 'TXN',   name: 'Texas Instruments',      type: 'value',  sector: 'Technology' },
  { ticker: 'ACN',   name: 'Accenture',              type: 'value',  sector: 'Technology' },
  { ticker: 'WMT',   name: 'Walmart',                type: 'value',  sector: 'Consumer' },
  { ticker: 'HD',    name: 'Home Depot',             type: 'value',  sector: 'Consumer' },
  { ticker: 'LOW',   name: "Lowe's",                 type: 'value',  sector: 'Consumer' },
  { ticker: 'MCD',   name: "McDonald's",             type: 'value',  sector: 'Consumer' },
  { ticker: 'DIS',   name: 'Walt Disney',            type: 'value',  sector: 'Consumer' },
  { ticker: 'CMCSA', name: 'Comcast',                type: 'value',  sector: 'Consumer' },
  { ticker: 'TGT',   name: 'Target',                 type: 'value',  sector: 'Consumer' },
  { ticker: 'PG',    name: 'Procter & Gamble',       type: 'value',  sector: 'Consumer' },
  { ticker: 'KO',    name: 'Coca-Cola',              type: 'value',  sector: 'Consumer' },
  { ticker: 'PEP',   name: 'PepsiCo',                type: 'value',  sector: 'Consumer' },
  { ticker: 'PM',    name: 'Philip Morris',          type: 'value',  sector: 'Consumer' },
  { ticker: 'MO',    name: 'Altria',                 type: 'value',  sector: 'Consumer' },
  { ticker: 'CL',    name: 'Colgate-Palmolive',      type: 'value',  sector: 'Consumer' },
  { ticker: 'KMB',   name: 'Kimberly-Clark',         type: 'value',  sector: 'Consumer' },
  { ticker: 'GIS',   name: 'General Mills',          type: 'value',  sector: 'Consumer' },
  { ticker: 'JNJ',   name: 'Johnson & Johnson',      type: 'value',  sector: 'Healthcare' },
  { ticker: 'MRK',   name: 'Merck',                  type: 'value',  sector: 'Healthcare' },
  { ticker: 'ABT',   name: 'Abbott Laboratories',    type: 'value',  sector: 'Healthcare' },
  { ticker: 'AMGN',  name: 'Amgen',                  type: 'value',  sector: 'Healthcare' },
  { ticker: 'TMO',   name: 'Thermo Fisher',          type: 'value',  sector: 'Healthcare' },
  { ticker: 'DHR',   name: 'Danaher',                type: 'value',  sector: 'Healthcare' },
  { ticker: 'UNH',   name: 'UnitedHealth',           type: 'value',  sector: 'Healthcare' },
  { ticker: 'ABBV',  name: 'AbbVie',                 type: 'value',  sector: 'Healthcare' },
  { ticker: 'BMY',   name: 'Bristol-Myers Squibb',   type: 'value',  sector: 'Healthcare' },
  { ticker: 'PFE',   name: 'Pfizer',                 type: 'value',  sector: 'Healthcare' },
  { ticker: 'GILD',  name: 'Gilead Sciences',        type: 'value',  sector: 'Healthcare' },
  { ticker: 'MDT',   name: 'Medtronic',              type: 'value',  sector: 'Healthcare' },
  { ticker: 'NOVO-B.CO', name: 'Novo Nordisk',       type: 'value',  sector: 'Healthcare' },
  { ticker: 'NEE',   name: 'NextEra Energy',         type: 'value',  sector: 'Utilities' },
  { ticker: 'DUK',   name: 'Duke Energy',            type: 'value',  sector: 'Utilities' },
  { ticker: 'SO',    name: 'Southern Company',       type: 'value',  sector: 'Utilities' },
  { ticker: 'D',     name: 'Dominion Energy',        type: 'value',  sector: 'Utilities' },
  { ticker: 'AEP',   name: 'American Electric Power',type: 'value',  sector: 'Utilities' },
  { ticker: 'EXC',   name: 'Exelon',                 type: 'value',  sector: 'Utilities' },
  { ticker: 'VZ',    name: 'Verizon',                type: 'value',  sector: 'Telecom' },
  { ticker: 'T',     name: 'AT&T',                   type: 'value',  sector: 'Telecom' },
  { ticker: 'LIN',   name: 'Linde',                  type: 'value',  sector: 'Materials' },
  { ticker: 'SHW',   name: 'Sherwin-Williams',       type: 'value',  sector: 'Materials' },
  { ticker: 'NEM',   name: 'Newmont',                type: 'value',  sector: 'Materials' },
  { ticker: 'FCX',   name: 'Freeport-McMoRan',       type: 'value',  sector: 'Materials' },
  // REIT
  { ticker: 'O',     name: 'Realty Income',          type: 'reit',   sector: 'REIT' },
  { ticker: 'VICI',  name: 'VICI Properties',        type: 'reit',   sector: 'REIT' },
  { ticker: 'PLD',   name: 'Prologis',               type: 'reit',   sector: 'REIT' },
  { ticker: 'PSA',   name: 'Public Storage',         type: 'reit',   sector: 'REIT' },
  { ticker: 'DLR',   name: 'Digital Realty',         type: 'reit',   sector: 'REIT' },
  { ticker: 'EQIX',  name: 'Equinix',                type: 'reit',   sector: 'REIT' },
  { ticker: 'AMT',   name: 'American Tower',         type: 'reit',   sector: 'REIT' },
  { ticker: 'CCI',   name: 'Crown Castle',           type: 'reit',   sector: 'REIT' },
  { ticker: 'SPG',   name: 'Simon Property Group',   type: 'reit',   sector: 'REIT' },
  { ticker: 'AVB',   name: 'AvalonBay Communities',  type: 'reit',   sector: 'REIT' },
  { ticker: 'EQR',   name: 'Equity Residential',     type: 'reit',   sector: 'REIT' },
  { ticker: 'WPC',   name: 'W. P. Carey',            type: 'reit',   sector: 'REIT' },
  { ticker: 'IRM',   name: 'Iron Mountain',          type: 'reit',   sector: 'REIT' },
  { ticker: 'ARE',   name: 'Alexandria Real Estate',  type: 'reit',   sector: 'REIT' },
  { ticker: 'WELL',  name: 'Welltower',              type: 'reit',   sector: 'REIT' },
  { ticker: 'VTR',   name: 'Ventas',                 type: 'reit',   sector: 'REIT' },
  { ticker: 'NNN',   name: 'NNN REIT',               type: 'reit',   sector: 'REIT' },
  { ticker: 'EXR',   name: 'Extra Space Storage',    type: 'reit',   sector: 'REIT' },
  { ticker: 'ESS',   name: 'Essex Property Trust',   type: 'reit',   sector: 'REIT' },
  { ticker: 'MAA',   name: 'Mid-America Apartment',  type: 'reit',   sector: 'REIT' },
  { ticker: 'UDR',   name: 'UDR Inc.',               type: 'reit',   sector: 'REIT' },
  { ticker: 'CPT',   name: 'Camden Property Trust',  type: 'reit',   sector: 'REIT' },
  { ticker: 'KIM',   name: 'Kimco Realty',           type: 'reit',   sector: 'REIT' },
  { ticker: 'REG',   name: 'Regency Centers',        type: 'reit',   sector: 'REIT' },
  { ticker: 'FRT',   name: 'Federal Realty',         type: 'reit',   sector: 'REIT' },
  { ticker: 'BXP',   name: 'Boston Properties',      type: 'reit',   sector: 'REIT' },
  // INTERNACIONAIS (bolsas de origem, plano Ultimate)
  { ticker: '2330.TW',   name: 'TSMC',                type: 'growth', sector: 'Technology' },
  { ticker: 'ASML.AS',   name: 'ASML',                type: 'growth', sector: 'Technology' },
  { ticker: 'NESN.SW',   name: 'NestlÃ©',              type: 'value',  sector: 'Consumer' },
  { ticker: 'TCEHY',     name: 'Tencent',             type: 'growth', sector: 'Technology' },
  { ticker: 'BABA',      name: 'Alibaba',             type: 'growth', sector: 'Technology' },
  { ticker: 'SIE.DE',    name: 'Siemens',             type: 'value',  sector: 'Industrials' },
  { ticker: 'MC.PA',     name: 'LVMH',                type: 'growth', sector: 'Consumer' },
  { ticker: 'ARM',       name: 'Arm Holdings',        type: 'growth', sector: 'Technology' },
  { ticker: '005930.KS', name: 'Samsung Electronics', type: 'growth', sector: 'Technology' },
  { ticker: '000660.KS', name: 'SK Hynix',            type: 'growth', sector: 'Technology' },
  { ticker: 'SAB.MC',    name: 'Banco Sabadell',      type: 'value',  sector: 'Finance' },
  { ticker: 'SAP.DE',    name: 'SAP',                 type: 'growth', sector: 'Technology' },
  { ticker: 'RACE.MI',   name: 'Ferrari',             type: 'growth', sector: 'Consumer' },
  { ticker: 'SAF.PA',    name: 'Safran',              type: 'value',  sector: 'Industrials' },
  { ticker: 'RHM.DE',    name: 'Rheinmetall',         type: 'value',  sector: 'Industrials' },
  { ticker: 'DG.PA',     name: 'Vinci',               type: 'value',  sector: 'Industrials' },
]
